version: '3.4'

services:
  lookup.api:
    image: lookup.api
    build:
      context: ./Services/Lookup.API
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  customers.api:
    image: customers.api
    build:
      context: ./Services/Customers.API
      dockerfile: Dockerfile
    depends_on: 
      - lookup.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  monolithtomicroservices:
    image: monolithtomicroservices
    build:
      context: ./MonolithToMicroservices
      dockerfile: Dockerfile
    depends_on:
      - lookup.api
      - customers.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80:80"